model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        n_classes: 8192
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: ldm.data.textzoom.multi_lmdbDataset
      params:
        roots: [ '/home/zhouyuxuan/latent-diffusion/textzoom/train1/',
                 '/home/zhouyuxuan/latent-diffusion/textzoom/train2/',]
#                 '/data2/zhouyuxuan/sr_data/IIIT5K',
#                 '/data2/zhouyuxuan/sr_data/COCO_Text',
#                 '/data2/zhouyuxuan/sr_data/ICDAR2013',
#                 '/data2/zhouyuxuan/sr_data/ICDAR2015',
#                 '/data2/zhouyuxuan/sr_data/synth90K_shuffle',
#                 '/data2/zhouyuxuan/sr_data/SynthAdd',
#                 '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_1_40',
#                 '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_41_80',
#                 '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_81_160',
#                 '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_161_200' ]
        #        size: 256
        #        degradation: bsrgan_light
        #        downscale_f: 4
        #        min_crop_f: 0.5
        #        max_crop_f: 1.0
        #        random_crop: true
    validation:
      target: ldm.data.textzoom.lmdbDataset_real
      params:
        root: '/home/zhouyuxuan/latent-diffusion/textzoom/test/easy'
        voc_type: 'all'
    #        size: 256
    #        degradation: bsrgan_light
    #        downscale_f: 4
    #        min_crop_f: 0.5
    #        max_crop_f: 1.0
    #        random_crop: true
    train_align_collate_fn:
      target: ldm.data.textzoom.alignCollate_realWTL_forVQGAN
      params:
        imgH: 64
        imgW: 256
        down_sample_scale: 4
        mask: false
        train: true
    val_align_collate_fn:
      target: ldm.data.textzoom.alignCollate_realWTL_forVQGAN
      params:
        imgH: 64
        imgW: 256
        down_sample_scale: 4
        mask: false
        train: false



