model:
  base_learning_rate: 1e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: LR_image
    image_size: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    conditioning_key: hybrid
    text_prior_enable: true
#    ckpt_path: '/home/zhouyuxuan/latent-diffusion/logs/2023-07-15T11-14-10_sr/checkpoints/last.ckpt'
#    ckpt_path: '/data/zhouyuxuan/ldm/model.ckpt'
#    ckpt_path: '/home/zhouyuxuan/latent-diffusion/logs/2023-03-26T11-06-49_sr/checkpoints/epoch=000071.ckpt'
#    ckpt_path: '/home/zhouyuxuan/latent-diffusion/logs/2023-03-25T23-36-50_sr/checkpoints/epoch=000113.ckpt'
#    ckpt_path: '/home/zhouyuxuan/latent-diffusion/logs/2023-03-25T19-56-32_sr/checkpoints/epoch=000003.ckpt'
    load_only_unet: false
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 160
        attention_resolutions:
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ckpt_path: '/home/zhouyuxuan/latent-diffusion/vqgan.ckpt'
#        ckpt_path: '/home/zhouyuxuan/latent-diffusion/logs/2023-03-25T13-38-13_custom_vqgan/checkpoints/epoch=000026.ckpt'
#        ckpt_path: '/home/zhouyuxuan/latent-diffusion/logs/2023-03-20T16-06-03_custom_vqgan/checkpoints/epoch=000140.ckpt'
#        ckpt_path: '/home/zhouyuxuan/latent-diffusion/AE/model.ckpt'
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.tp_generator.TP_generator
      params:
        imgH: 32
        recognizer_path: '/home/zhouyuxuan/latent-diffusion/crnn.pth'


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    wrap: false
    num_workers: 4
    train:
      target: ldm.data.textzoom.multi_lmdbDataset
      params:
        roots: ['/home/zhouyuxuan/latent-diffusion/textzoom/train1/',
                '/home/zhouyuxuan/latent-diffusion/textzoom/train2/',
#                '/data2/zhouyuxuan/sr_data/IIIT5K',
#                '/data2/zhouyuxuan/sr_data/COCO_Text',
#                '/data2/zhouyuxuan/sr_data/ICDAR2013',
#                '/data2/zhouyuxuan/sr_data/ICDAR2015',
#                '/data2/zhouyuxuan/sr_data/synth90K_shuffle',
#                '/data2/zhouyuxuan/sr_data/SynthAdd',
#                '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_1_40',
#                '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_41_80',
#                '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_81_160',
#                '/data2/zhouyuxuan/sr_data/SynthText800K_shuffle_161_200'
        ]
#        size: 256
#        degradation: bsrgan_light
#        downscale_f: 4
#        min_crop_f: 0.5
#        max_crop_f: 1.0
#        random_crop: true
    validation:
      target: ldm.data.textzoom.lmdbDataset_real
      params:
        root: '/home/zhouyuxuan/latent-diffusion/textzoom/test/easy'
        voc_type: 'all'
#        size: 256
#        degradation: bsrgan_light
#        downscale_f: 4
#        min_crop_f: 0.5
#        max_crop_f: 1.0
#        random_crop: true
    train_align_collate_fn:
      target: ldm.data.textzoom.alignCollate_realWTL
      params:
        imgH: 64
        imgW: 256
        down_sample_scale: 4
        mask: false
        train: true
    val_align_collate_fn:
      target: ldm.data.textzoom.alignCollate_realWTL
      params:
        imgH: 64
        imgW: 256
        down_sample_scale: 4
        mask: false
        train: false



